spring:
  profiles:
    active: ["dev"]

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: false
        format_sql: true
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: none
        default_batch_fetch_size: 100

jwt:
  secret: "ServerApplication-Secret-Key-For-JWT-Token-Generation-Must-Be-At-Least-256-Bits-Long-For-HS256-Algorithm"
  accessTokenExpiration: 3600000
  refreshTokenExpiration: 86400000